<?php
/**
 * intake_link.php – public, token-gated pre-intake form.
 *
 * Reached by patients via a WhatsApp link. No login required — the
 * per-submission token generated by whatsapp_form.php is the credential.
 * On POST, the form fields are stored on the matching submission row.
 */

require_once __DIR__ . '/app/config/session.php';
require_once __DIR__ . '/app/controllers/WhatsAppFormController.php';

$controller = new WhatsAppFormController();

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $controller->submitForm();
} else {
    $controller->showForm();
}
